AWSTemplateFormatVersion: 2010-09-09
Description: "Create EC2 instance"
           
Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod
      - qa
Mappings:
  EnvMap:
    dev:
      InstanceType: "t2.micro"
      name: "dev"
      ImageId: "ami-02ee763250491e04a"
    prod:
      InstanceType: "t2.large"
      name: "prod"
      ImageId: "ami-04ff9e9b51c1f62ca"
    qa:
      InstanceType: "t2.small"
      name: "qa"
      ImageId: "ami-02248c9d6ba0b9e12"
Resources:
  Instance: #logical id
    Type: AWS::EC2::Instance #type
    Properties:
      InstanceType: !FindInMap [EnvMap, !Ref Environment, InstanceType]
      ImageId: !FindInMap [EnvMap, !Ref Environment, ImageId]
      SubnetId: subnet-0f8fc8201e1007095
      KeyName: Kp11
      Tags:
        - Key: "Name"
          Value: !FindInMap [EnvMap, !Ref Environment, name]
      UserData:
        Fn::Base64:
          Fn::Join:
            - |+

            - - '#!/bin/bash'
              - apt-get update
              - apt-get install apache2 -y
Outputs:
    InstanceName:
        Value: !FindInMap [EnvMap, !Ref Environment, name]
    ImageId:
        Value: !FindInMap [EnvMap, !Ref Environment, ImageId]